/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financialcalculators;

/**
 *
 * @author mwrai
 */
public class AutoLoanFrame extends javax.swing.JFrame {

    /**
     * Creates new form AutoLoanFrame
     */
    public AutoLoanFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutoLoanTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        inputVehiclePrice = new javax.swing.JTextField();
        inputLoanTerm2 = new javax.swing.JTextField();
        inputIntRate2 = new javax.swing.JTextField();
        inputDownPayment2 = new javax.swing.JTextField();
        inputTradeIn2 = new javax.swing.JTextField();
        inputSalesTax2 = new javax.swing.JTextField();
        calculateMonthlyPay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TotalPriceresult1 = new javax.swing.JLabel();
        TotalPriceresult2 = new javax.swing.JLabel();
        TotalPriceresult3 = new javax.swing.JLabel();
        TotalPriceresult4 = new javax.swing.JLabel();
        TotalPriceresult5 = new javax.swing.JLabel();
        TotalPriceresult6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        monthlyPay = new javax.swing.JTextField();
        inputLoanTerm = new javax.swing.JTextField();
        inputIntRate = new javax.swing.JTextField();
        inputDownPayment = new javax.swing.JTextField();
        inputTradeIn = new javax.swing.JTextField();
        inputSalesTax = new javax.swing.JTextField();
        calculateTotalPrice = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MonthlyPaymentresult6 = new javax.swing.JLabel();
        MonthlyPaymentresult5 = new javax.swing.JLabel();
        MonthlyPaymentresult4 = new javax.swing.JLabel();
        MonthlyPaymentresult3 = new javax.swing.JLabel();
        MonthlyPaymentresult2 = new javax.swing.JLabel();
        MonthlyPaymentresult1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputVehiclePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVehiclePriceActionPerformed(evt);
            }
        });

        calculateMonthlyPay.setText("calculate");
        calculateMonthlyPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMonthlyPayActionPerformed(evt);
            }
        });

        jLabel1.setText("Auto Price");

        jLabel2.setText("Loan Term");

        jLabel3.setText("Interest Rate");

        jLabel4.setText("Down Payment");

        jLabel5.setText("Trade In Value");

        jLabel6.setText("Sales Tax");

        TotalPriceresult1.setText("Monthly Loan Payment: ");

        TotalPriceresult2.setText("Total Loan Amount: ");

        TotalPriceresult3.setText("Total Sales Tax: ");

        TotalPriceresult4.setText("Total of all Loan Payments:");

        TotalPriceresult5.setText("Total Loan Interest:");

        TotalPriceresult6.setText("Total Cost: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculateMonthlyPay)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputSalesTax2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(inputTradeIn2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDownPayment2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputIntRate2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputLoanTerm2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputVehiclePrice, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalPriceresult1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPriceresult2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPriceresult3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPriceresult6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPriceresult5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPriceresult4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputVehiclePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(TotalPriceresult1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputLoanTerm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TotalPriceresult2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputIntRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDownPayment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(TotalPriceresult3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalPriceresult4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTradeIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TotalPriceresult5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSalesTax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TotalPriceresult6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculateMonthlyPay)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        AutoLoanTab.addTab("Total Price", jPanel1);

        calculateTotalPrice.setText("calculate");
        calculateTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateTotalPriceActionPerformed(evt);
            }
        });

        jLabel7.setText("Monthly Payment");

        jLabel8.setText("Loan Term");

        jLabel9.setText("Interest Rate");

        jLabel10.setText("Down Payment");

        jLabel11.setText("Trade In Value");

        jLabel12.setText("Sales Tax");

        MonthlyPaymentresult6.setText("Total Cost: ");

        MonthlyPaymentresult5.setText("Total Loan Interest:");

        MonthlyPaymentresult4.setText("Total of all Loan Payments:");

        MonthlyPaymentresult3.setText("Total Sales Tax: ");

        MonthlyPaymentresult2.setText("Total Loan Amount: ");

        MonthlyPaymentresult1.setText("Monthly Loan Payment: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calculateTotalPrice)
                    .addComponent(monthlyPay)
                    .addComponent(inputLoanTerm)
                    .addComponent(inputIntRate)
                    .addComponent(inputDownPayment)
                    .addComponent(inputTradeIn)
                    .addComponent(inputSalesTax))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonthlyPaymentresult1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyPaymentresult2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyPaymentresult3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyPaymentresult6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyPaymentresult5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyPaymentresult4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthlyPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputLoanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDownPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTradeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MonthlyPaymentresult1)
                                .addGap(28, 28, 28))
                            .addComponent(MonthlyPaymentresult2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22)
                        .addComponent(MonthlyPaymentresult3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthlyPaymentresult4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthlyPaymentresult5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthlyPaymentresult6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculateTotalPrice)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        AutoLoanTab.addTab("Monthly Payment", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AutoLoanTab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AutoLoanTab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateMonthlyPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMonthlyPayActionPerformed
        // TODO add your handling code here:
        double vehiclePrice = Double.parseDouble(inputVehiclePrice.getText());
        int loanTerm = Integer.parseInt(inputLoanTerm2.getText());
        double intRate = Double.parseDouble(inputIntRate2.getText());
        double downPayment = Double.parseDouble(inputDownPayment2.getText());
        double tradeIn = Double.parseDouble(inputTradeIn2.getText());
        double salesTax = Double.parseDouble(inputSalesTax2.getText());
        double monthlyPayment = AutoLoan.monthlyPay(vehiclePrice, loanTerm, intRate, tradeIn, downPayment, salesTax);
        double totalCost = AutoLoan.totalCost2(vehiclePrice, downPayment, tradeIn, salesTax);
        double totalSalesTax = (vehiclePrice-downPayment)*(salesTax/100);
        double totalPaid = loanTerm*monthlyPayment;
        double loanInterest = totalPaid-totalCost;
        double totalValue = totalPaid+downPayment+tradeIn;
        
        
        TotalPriceresult1.setText(String.format("Monthly Loan Payment: %.02f",monthlyPayment));
        TotalPriceresult2.setText(String.format("Total Loan Amount: %.02f",totalCost));
        TotalPriceresult3.setText(String.format("Total Sales Tax: %.02f",totalSalesTax));
        TotalPriceresult4.setText(String.format("Total of %d Loan Payments: %.02f",loanTerm,totalPaid));
        TotalPriceresult5.setText(String.format("Total Loan Interest: %.02f",loanInterest));
        TotalPriceresult6.setText(String.format("Total Cost: %.02f",totalValue));
        
    }//GEN-LAST:event_calculateMonthlyPayActionPerformed

    private void inputVehiclePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVehiclePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVehiclePriceActionPerformed

    private void calculateTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateTotalPriceActionPerformed
        // TODO add your handling code here:
        double monthlyPayment = Double.parseDouble(monthlyPay.getText());
        int loanTerm = Integer.parseInt(inputLoanTerm.getText());
        double intRate = Double.parseDouble(inputIntRate.getText());
        double downPayment = Double.parseDouble(inputDownPayment.getText());
        double tradeIn = Double.parseDouble(inputTradeIn.getText());
        double salesTax = Double.parseDouble(inputSalesTax.getText());
        double totalLoanAmount = AutoLoan.totalLoanAmount(monthlyPayment, intRate, loanTerm);
        double vehiclePrice = AutoLoan.vehiclePrice(monthlyPayment, loanTerm, intRate, tradeIn, downPayment, salesTax, totalLoanAmount);
        double totalSalesTax = AutoLoan.totalTax(salesTax, downPayment, totalLoanAmount);
        double totalPaid = monthlyPayment*loanTerm;
        double loanInterest = totalPaid-totalLoanAmount;
        double totalValue = totalPaid+downPayment+tradeIn;
        MonthlyPaymentresult1.setText(String.format("Monthly Loan Payment: $%,.02f",vehiclePrice));
        MonthlyPaymentresult2.setText(String.format("Total Loan Amount: $%,.02f",totalLoanAmount));
        MonthlyPaymentresult3.setText(String.format("Total Sales Tax: $%,.02f",totalSalesTax));
        MonthlyPaymentresult4.setText(String.format("Total of %d Loan Payments: $%,.02f",loanTerm,totalPaid));
        MonthlyPaymentresult5.setText(String.format("Total Loan Interest: $%,.02f",loanInterest));
        MonthlyPaymentresult6.setText(String.format("Total Cost: $%,.02f",totalValue));
    }//GEN-LAST:event_calculateTotalPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoLoanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AutoLoanTab;
    private javax.swing.JLabel MonthlyPaymentresult1;
    private javax.swing.JLabel MonthlyPaymentresult2;
    private javax.swing.JLabel MonthlyPaymentresult3;
    private javax.swing.JLabel MonthlyPaymentresult4;
    private javax.swing.JLabel MonthlyPaymentresult5;
    private javax.swing.JLabel MonthlyPaymentresult6;
    private javax.swing.JLabel TotalPriceresult1;
    private javax.swing.JLabel TotalPriceresult2;
    private javax.swing.JLabel TotalPriceresult3;
    private javax.swing.JLabel TotalPriceresult4;
    private javax.swing.JLabel TotalPriceresult5;
    private javax.swing.JLabel TotalPriceresult6;
    private javax.swing.JButton calculateMonthlyPay;
    private javax.swing.JButton calculateTotalPrice;
    private javax.swing.JTextField inputDownPayment;
    private javax.swing.JTextField inputDownPayment2;
    private javax.swing.JTextField inputIntRate;
    private javax.swing.JTextField inputIntRate2;
    private javax.swing.JTextField inputLoanTerm;
    private javax.swing.JTextField inputLoanTerm2;
    private javax.swing.JTextField inputSalesTax;
    private javax.swing.JTextField inputSalesTax2;
    private javax.swing.JTextField inputTradeIn;
    private javax.swing.JTextField inputTradeIn2;
    private javax.swing.JTextField inputVehiclePrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField monthlyPay;
    // End of variables declaration//GEN-END:variables
}
