/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabri
 */
public class buyvsrentcalc extends javax.swing.JFrame {

    /**
     * Creates new form buyvsrentcalc
     */
    public buyvsrentcalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(210, 290, 71, 22);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(210, 330, 71, 22);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(210, 360, 71, 22);

        jLabel4.setText("Down payment");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 96, 16);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12);
        jTextField12.setBounds(210, 390, 71, 22);

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField24);
        jTextField24.setBounds(210, 450, 71, 22);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(210, 420, 71, 22);

        jLabel2.setText("Home price ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 96, 16);

        jLabel5.setText("Interest rate ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 82, 16);

        jLabel6.setText("Loan term");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 82, 16);

        jLabel7.setText("Buying closing costs");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 220, 110, 16);

        jLabel8.setText("Property tax ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 260, 82, 16);

        jLabel9.setText("Property tax increase");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 290, 110, 22);

        jLabel10.setText("Home insurance ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 330, 90, 16);

        jLabel11.setText("HOA fee");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 360, 82, 16);

        jLabel12.setText("Maintenance cost ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 390, 110, 16);

        jLabel13.setText("Home value appreciation ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 420, 136, 16);

        jLabel14.setText("cost/insurance increase ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 450, 138, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 50, 71, 22);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 90, 71, 22);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 130, 71, 22);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(210, 170, 71, 22);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(210, 210, 71, 22);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(210, 250, 71, 22);

        jLabel25.setText("Tax filing status");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(420, 410, 138, 16);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField20);
        jTextField20.setBounds(670, 320, 77, 22);

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField21);
        jTextField21.setBounds(670, 360, 77, 22);

        jLabel16.setText("Monthly rental fee");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(420, 43, 119, 43);

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField23);
        jTextField23.setBounds(668, 212, 77, 22);

        jLabel17.setText("Rental fee increase ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(420, 100, 119, 16);

        jLabel18.setText("Renter's insurance ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(420, 140, 99, 19);

        jLabel19.setText("Security deposit");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(420, 180, 98, 16);

        jLabel20.setText("Upfront cost ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(420, 210, 107, 16);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField15);
        jTextField15.setBounds(668, 56, 77, 22);

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16);
        jTextField16.setBounds(668, 96, 77, 22);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17);
        jTextField17.setBounds(668, 130, 77, 22);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18);
        jTextField18.setBounds(670, 170, 77, 22);

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField19);
        jTextField19.setBounds(670, 290, 77, 22);

        jLabel22.setText("average investment return ");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(420, 320, 141, 16);

        jLabel23.setText("Marginal federal text rate ");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(420, 290, 135, 16);

        jLabel24.setText("Marginal state tax rate ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(420, 360, 138, 16);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("CALCULATE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 470, 90, 40);

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("      CLEAR ");
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setOpaque(true);
        jLabel21.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel21AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(720, 470, 80, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "single", "married filing jointly ", "married filling separately", "head of household ", "quaified widow" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(610, 400, 180, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 470, 320, 40);

        jLabel3.setBackground(java.awt.Color.gray);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Home Rent");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 10, 340, 20);

        jLabel15.setBackground(java.awt.Color.gray);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Your Information");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 250, 330, 20);

        jLabel26.setBackground(java.awt.Color.gray);
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Home Purchase");
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel26.setOpaque(true);
        getContentPane().add(jLabel26);
        jLabel26.setBounds(20, 10, 270, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        try {
            double taxIncrease = Double.parseDouble(jTextField7.getText());
            JOptionPane.showMessageDialog(this, "Property Tax Increase: " + taxIncrease + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid property tax increase entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        try {
            double homeInsurance = Double.parseDouble(jTextField8.getText());
            JOptionPane.showMessageDialog(this, "Home Insurance: $" + homeInsurance);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid home insurance entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        try {
            double hoaFee = Double.parseDouble(jTextField9.getText());
            JOptionPane.showMessageDialog(this, "HOA Fee: $" + hoaFee);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid HOA fee entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        try {
            double maintenanceCosts = Double.parseDouble(jTextField10.getText());
            JOptionPane.showMessageDialog(this, "Maintenance Costs: $" + maintenanceCosts);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid maintenance costs entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        try {
            // Ensure jTextField12 is correctly declared and initialized
            double insuranceIncrease = Double.parseDouble(jTextField12.getText());

            // Use null if this is not a JFrame/JDialog
            JOptionPane.showMessageDialog(null, "Insurance Cost Increase: " + insuranceIncrease + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid insurance cost increase entered.");
        }
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        try {
            double homeValueAppreciation = Double.parseDouble(jTextField11.getText());
            JOptionPane.showMessageDialog(this, "Home Value Appreciation: " + homeValueAppreciation + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid home value appreciation entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        {// Parse the input as a double
            double homePrice = Double.parseDouble(jTextField1.getText());
            // Print the home price to the console
            System.out.println("Home Price entered: $" + homePrice);
            // Handle invalid input
            System.out.println("Please enter a valid number.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        try {
            double downPayment = Double.parseDouble(jTextField4.getText());
            JOptionPane.showMessageDialog(this, "Down Payment: $" + downPayment);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid down payment entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        try {
            double interestRate = Double.parseDouble(jTextField5.getText());
            JOptionPane.showMessageDialog(this, "Interest Rate: " + interestRate + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid interest rate entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        try {
            int loanTerm = Integer.parseInt(jTextField4.getText());
            JOptionPane.showMessageDialog(this, "Loan Term: " + loanTerm + " years");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid loan term entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        try {
            double closingCosts = Double.parseDouble(jTextField5.getText());
            JOptionPane.showMessageDialog(this, "Buying Closing Costs: $" + closingCosts);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid closing costs entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        try {
            double propertyTax = Double.parseDouble(jTextField6.getText());
            JOptionPane.showMessageDialog(this, "Property Tax: $" + propertyTax);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid property tax entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        try {
            double investmentReturn = Double.parseDouble(jTextField20.getText());
            JOptionPane.showMessageDialog(this, "Average Investment Return: " + investmentReturn + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid investment return.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        try {
            double stateTaxRate = Double.parseDouble(jTextField21.getText());
            JOptionPane.showMessageDialog(this, "Marginal State Tax Rate: " + stateTaxRate + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid state tax rate.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        try {
            double upfrontCost = Double.parseDouble(jTextField18.getText());
            JOptionPane.showMessageDialog(this, "Upfront Cost: $" + upfrontCost);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid upfront cost.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        try {
            double rentalFee = Double.parseDouble(jTextField16.getText());
            JOptionPane.showMessageDialog(this, "Monthly Rental Fee: $" + rentalFee);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid monthly rental fee entered.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        try {
            double increasedRentalFee = Double.parseDouble(jTextField16.getText()) * (1 + Double.parseDouble(jTextField15.getText()) / 100);
            JOptionPane.showMessageDialog(this, "New Rental Fee: $" + increasedRentalFee);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        try {
            double rentersInsurance = Double.parseDouble(jTextField16.getText());
            JOptionPane.showMessageDialog(this, "Renter's Insurance: $" + rentersInsurance);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid renter's insurance.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        try {
            double securityDeposit = Double.parseDouble(jTextField17.getText());
            JOptionPane.showMessageDialog(this, "Security Deposit: $" + securityDeposit);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid security deposit.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        try {
            double marginalTaxRate = Double.parseDouble(jTextField19.getText());
            JOptionPane.showMessageDialog(this, "Marginal Federal Tax Rate: " + marginalTaxRate + "%");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid tax rate.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Gather input from the text fields
            double homePrice;
            homePrice = Double.parseDouble(jTextField1.getText());
            double downPayment = Double.parseDouble(jTextField4.getText());
            double interestRate = Double.parseDouble(jTextField5.getText()) / 100;
            int loanTerm = Integer.parseInt(jTextField6.getText());
            double buyingClosingCosts = Double.parseDouble(jTextField7.getText());
            double propertyTax = Double.parseDouble(jTextField8.getText()) / 100;
            double propertyTaxIncrease = Double.parseDouble(jTextField9.getText()) / 100;
            double homeInsurance = Double.parseDouble(jTextField10.getText());
            double hoaFee = Double.parseDouble(jTextField11.getText());
            double maintenanceCost = Double.parseDouble(jTextField12.getText());
            double homeValueAppreciation = Double.parseDouble(jTextField13.getText()) / 100;
            double costInsuranceIncrease = Double.parseDouble(jTextField24.getText()) / 100;
            double monthlyRentalFee = Double.parseDouble(jTextField15.getText());
            double rentalFeeIncrease = Double.parseDouble(jTextField16.getText()) / 100;
            double rentersInsurance = Double.parseDouble(jTextField17.getText());
            double securityDeposit = Double.parseDouble(jTextField18.getText());
            double upfrontCost = Double.parseDouble(jTextField23.getText());
            double marginalFederalTaxRate = Double.parseDouble(jTextField19.getText()) / 100;
            double averageInvestmentReturn = Double.parseDouble(jTextField20.getText()) / 100;
            double marginalStateTaxRate = Double.parseDouble(jTextField21.getText()) / 100;
            String taxFilingStatus = (String) jComboBox1.getSelectedItem(); // Assuming a dropdown or simple text field
            // Calculate total cost for buying
            double loanAmount = homePrice - downPayment;
            double annualLoanPayment = loanAmount * (interestRate / (1 - Math.pow(1 + interestRate, -loanTerm * 12)));
            double totalBuyingCost = downPayment + buyingClosingCosts + (annualLoanPayment * loanTerm) +
            (propertyTax * homePrice) + (homeInsurance * loanTerm) +
            (hoaFee * 12 * loanTerm) + (maintenanceCost * loanTerm);

            // Calculate total cost for renting
            double totalRentingCost = (monthlyRentalFee * 12 * loanTerm) + rentersInsurance +
            (rentalFeeIncrease * monthlyRentalFee * loanTerm) + upfrontCost;

            // Display results
            String result;
            if (totalBuyingCost < totalRentingCost) {
                jLabel1.setText(String.format("Buying is more cost-effective over %d years.",loanTerm));
                result = "Buying is more cost-effective over " + loanTerm + " years.";
            } else {
                jLabel1.setText(String.format("Renting is more cost-effective over %d years.",loanTerm));
                result = "Renting is more cost-effective over " + loanTerm + " years.";
            }
            System.out.println(result);

        } catch (NumberFormatException e) {
            System.out.println("Please ensure all fields contain valid numbers.");
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel21AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel21AncestorAdded
        // Clear all text fields
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField21.setText("");

        // Reset the combo box (example for tax filing status)
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyvsrentcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyvsrentcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyvsrentcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyvsrentcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyvsrentcalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}